version: '3.8'

services:
  mysql-container:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - ./mysql_volume:/var/lib/mysql
    ports:
      - "3306:3306"

